<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>scopeName</key>
	<string>text.robot</string>

	<key>uuid</key>
	<string>a7fae509-bc8d-451e-b5fc-a47feb9d2a9e</string>

  <key>fileTypes</key>
  <array>
    <string>robot</string>
  </array>

	<key>name</key>
	<string>RobotFramework</string>

  <key>repository</key>
  <dict>
    <key>comment</key>
		<dict>
			<key>match</key>
			<string>(?:^|\t+| {2,})(#.*)$</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>comment.line.robot</string>
        </dict>
      </dict>
		</dict>

    <key>variables</key>
		<dict>
			<key>match</key>
			<string>([$@&amp;%]\{)(.*?)(\})</string>

      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.begin.robot</string>
        </dict>

        <key>2</key>
        <dict>
          <key>name</key>
          <string>variable.language.robot</string>
        </dict>

        <key>3</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.end.robot</string>
        </dict>
      </dict>
		</dict>

    <key>documentation</key>
		<dict>
			<key>begin</key>
			<string>(?i)^(\s*\[?Documentation\]?)(?: {2,}+| ?\t+| ?$)(.*)</string>

      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.method.robot</string>
        </dict>

        <key>2</key>
        <dict>
          <key>name</key>
          <string>string.unquoted.robot</string>
        </dict>
      </dict>

			<key>end</key>
			<string>^(?!\s*+\.\.\.)</string>

      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>^(\s*+\.\.\.)?( {2,}+| ?\t+| ?$)(.*)</string>

          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.robot</string>
            </dict>

            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.unquoted.robot</string>
            </dict>
          </dict>

        </dict>
      </array>

		</dict>
  </dict>

	<key>patterns</key>
	<array>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#variables</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#documentation</string>
    </dict>
		<dict>
			<key>match</key>
			<string>(?i)^\*+\s*(settings?|metadata|(user )?keywords?|test ?cases?|variables?)(.*)</string>
			<key>name</key>
			<string>string.robot.header</string>
		</dict>
		<!--<dict>
			<key>begin</key>
			<string>(?i)^\s*\[?Documentation\]?</string>
			<key>end</key>
			<string>^(?!\s*+\.\.\.)</string>
			<key>name</key>
			<string>comment</string>
		</dict>-->
    <!--
    <dict>
			<key>name</key>
			<string>string.robot.header</string>
			<key>comment</key>
			<string>Settings table</string>
			<key>begin</key>
			<string>(?i)^(\*+\s*)(settings?)(.*)$</string>
			<key>end</key>
			<string>(?i)^(?:\*+\s*)(?:settings?|metadata|(user )?keywords?|test ?cases?|variables?)(?:.*)$</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
      </array>
    </dict>-->
    <!--<dict>
			<key>name</key>
			<string>comment</string>
			<key>begin</key>
			<string>(?i)^\s*\[?Documentation\]?</string>
			<key>end</key>
			<string>^(?!\s*+\.\.\.)</string>
      <key>contentName</key>
      <string>storage.robot.documentation</string>
		</dict>-->
		<dict>
			<key>match</key>
			<string>\[.*?\]</string>
			<key>name</key>
			<string>storage.type.method.robot</string>
		</dict>
		<!--<dict>
			<key>match</key>
			<string>(\$\{.*?\})|(@\{.*?\})</string>
			<key>name</key>
			<string>variable.language.robot</string>
		</dict>-->
		<dict>
			<key>begin</key>
			<string>(^[^ \t\*\n\|]+)|((?&lt;=^\|)\s+[^ \t\*\n\|]+)</string>
			<key>end</key>
			<string>\s{2}|\t|$|\s+(?=\|)</string>
			<key>name</key>
			<string>keyword.control.robot</string>
		</dict>
	</array>
</dict>
</plist>
